### ISSUE TITLE
执行命令报错

### ISSUE THREAD

**Issue by fengshuo1992** [yan998/SelectorsUnrefs#1]
获取所有的protocol中的方法...
Traceback (most recent call last):
  File "FindSelectorsUnrefs.py", line 309, in <module>
    unref_sels = unref_selectors(app_path, project_path)
  File "FindSelectorsUnrefs.py", line 231, in unref_selectors
    protocol_sels = protocol_selectors(path, project_path)
  File "FindSelectorsUnrefs.py", line 151, in protocol_selectors
    header_protocol_sels = header_protocol_selectors(header_path)
  File "FindSelectorsUnrefs.py", line 80, in header_protocol_selectors
    for line in file.readlines():
  File "/Users/gzlx/opt/anaconda3/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 2340: invalid start byte

这个是怎么回事呢

**Comment by qpc2015** [comment]
Traceback (most recent call last):
  File "FindSelectorsUnrefs.py", line 309, in <module>
    unref_sels = unref_selectors(app_path, project_path)
  File "FindSelectorsUnrefs.py", line 231, in unref_selectors
    protocol_sels = protocol_selectors(path, project_path)
  File "FindSelectorsUnrefs.py", line 151, in protocol_selectors
    header_protocol_sels = header_protocol_selectors(header_path)
  File "FindSelectorsUnrefs.py", line 80, in header_protocol_selectors
    for line in file.readlines():
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 2340: invalid start byte

项目名称有中文，请问可以解决吗

**Comment by KillWilde** [comment]
获取所有的protocol中的方法...
Traceback (most recent call last):
  File "/Users/tonystark/Downloads/Performance-main/FindSelectorsUnrefs.py", line 309, in <module>
    unref_sels = unref_selectors(app_path, project_path)
  File "/Users/tonystark/Downloads/Performance-main/FindSelectorsUnrefs.py", line 231, in unref_selectors
    protocol_sels = protocol_selectors(path, project_path)
  File "/Users/tonystark/Downloads/Performance-main/FindSelectorsUnrefs.py", line 151, in protocol_selectors
    header_protocol_sels = header_protocol_selectors(header_path)
  File "/Users/tonystark/Downloads/Performance-main/FindSelectorsUnrefs.py", line 80, in header_protocol_selectors
    for line in file.readlines():
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 2340: invalid start byte.  



蛋疼

**Comment by OceanLiHaiYang** [comment]
都是一样的问题

**Comment by miao3723** [comment]
用 python 2版本 不要用 3
